# Descripció

Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy. 

## <span style='color:Blue'>Nivell 1</span>

### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [20]:
import numpy as np

def resumEstadistic(arr):
    if arr.ndim > 1:
        print("Error: aquesta funció només admet numpy arrays d'una dimensió.", end = "\n")
        print("-" * 80)
        return
    print("Numpy array:", arr)
    print()
    print("La suma dels valors és", np.sum(arr))
    print()
    print("El valor màxim és", np.max(arr))
    print("El valor mínim és", np.min(arr))
    print()
    print("La mitja dels valors és:", np.mean(arr), end = "\n")
    print()
        
    print("El primer quartil és:", np.percentile(arr, 25))
    print("La mitjana dels valors és:", np.median(arr), end = "\n")
    print("El tercer quartil és:", np.percentile(arr, 75))
    print()
    print("La desviació estàndar és:", np.std(arr), end = "\n")
    
    
# Referència:
# https://manualestutor.com/programacion/numpy-al-descubierto-una-guia-para-principiantes-sobre-estadisticas-con-numpy/
 


In [21]:
# nparray que donarà error
arr2D = np.array([[1,2,3,4,5], [6,7,8,9,10]])
resumEstadistic(arr2D)

Error: aquesta funció només admet numpy arrays d'una dimensió.
--------------------------------------------------------------------------------


In [24]:
# nparray correcte, cas 1
arr1D = np.array([1, 2, 3, 4, 5, 20])
resumEstadistic(arr1D)

Numpy array: [ 1  2  3  4  5 20]
La suma dels valors és 35

El valor màxim és 20
El valor mínim és 1

La mitja dels valors és: 5.833333333333333

El primer quartil és: 2.25
La mitjana dels valors és: 3.5
El tercer quartil és: 4.75
La desviació estàndar és: 6.465721580423608


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [ ]:
# Nota: per l'enunciat no queda clar si el 100 ha d'estar inclòs o no.
# Suposarem que SÍ.

In [27]:
def quadratNxN(n):
    return np.random.randint(101, size=(n, n))

n = 5
print("Array ", n, "x", n)
print(quadratNxN(5))
print("-" * 20)
n = 2
print("Array ", n, "x", n)
print(quadratNxN(2))

Array  5 x 5
[[89 53 34 13 14]
 [83 17 52 76 49]
 [19 27 61 65  6]
 [21 18 19 59 28]
 [85 48 93 71 33]]
--------------------
Array  2 x 2
[[28 65]
 [75 10]]


### Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 

In [32]:
def sumRowsColumns(arr):
    print("La suma de les columnes és:", np.sum(arr, axis=0))
    print("La suma de les fileres és:", np.sum(arr, axis=1))

arr = np.array([[0, 10], [100, 1000]])
print(arr)
sumRowsColumns(arr)

[[   0   10]
 [ 100 1000]]
La suma de les columnes és: [ 100 1010]
La suma de les fileres és: [  10 1100]


### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [35]:
def rowsAndColumns(arr):
    print("Columnes és:", np.array(arr, axis=0))
    print("Fileres és:", np.array(arr, axis=1))

arr = np.array([[0, 10], [100, 1000]])
print(arr)
# rowsAndColumns(arr)
print(arr[:, 0])
print(arr[:, 1])

[[   0   10]
 [ 100 1000]]
[  0 100]
[  10 1000]


In [40]:
arr1 = np.array([[1,1], [2,2], [3,3]])



In [41]:
import geopandas

ModuleNotFoundError: No module named 'geopandas'

In [44]:
import chart_studio

ModuleNotFoundError: No module named 'chart_studio'